# Generated by Django 5.1.3 on 2024-11-05 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cargo_name', models.CharField(max_length=225, verbose_name='Krovinio pavadinimas')),
                ('quantity', models.FloatField(verbose_name='Kiekis litrais arba kg')),
                ('vehicle_make', models.CharField(max_length=100, verbose_name='Automobilio markė')),
                ('vehicle_plate', models.CharField(max_length=20, verbose_name='Valstybinis numeris')),
                ('load_location', models.CharField(max_length=255, verbose_name='Pakrovimo vieta')),
                ('unload_location', models.CharField(max_length=255, verbose_name='Vairuotojo vardas, pavardė')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
