# Generated by Django 5.1.3 on 2024-11-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='driver_name',
            field=models.CharField(default='', max_length=255, verbose_name='Vairuotojo vardas, pavardė'),
        ),
        migrations.AlterField(
            model_name='document',
            name='unload_location',
            field=models.CharField(max_length=255, verbose_name='Iškrovimo vieta'),
        ),
    ]
