# Generated by Django 5.1.3 on 2024-12-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='document',
            name='email',
        ),
        migrations.RemoveField(
            model_name='document',
            name='km_price',
        ),
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('freight', 'Krovinio važtaraštis'), ('platform', 'Mobilios alkūninės darbo platformos aktas')], default='freight', max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='cargo_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
