# Generated by Django 5.1.3 on 2025-01-03 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_client_code_document_delivery_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='delivery',
            new_name='delivered_by',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='responsible_person',
            new_name='received_by',
        ),
        migrations.RemoveField(
            model_name='document',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='document',
            name='responsible_signature',
        ),
    ]
