# Generated by Django 5.1.3 on 2025-01-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_rename_delivery_document_delivered_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='cargo_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Krovinio pavadinimas'),
        ),
        migrations.AlterField(
            model_name='document',
            name='client_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Užsakovo kodas'),
        ),
        migrations.AlterField(
            model_name='document',
            name='client_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Užsakovas'),
        ),
        migrations.AlterField(
            model_name='document',
            name='daily_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Paros kaina'),
        ),
        migrations.AlterField(
            model_name='document',
            name='days_worked',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Dirbtos paros'),
        ),
        migrations.AlterField(
            model_name='document',
            name='delivered_by',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nuomotojo įrangą pristatęs asmuo'),
        ),
        migrations.AlterField(
            model_name='document',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Nuomos pabaigos data'),
        ),
        migrations.AlterField(
            model_name='document',
            name='km_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Kilometro kaina'),
        ),
        migrations.AlterField(
            model_name='document',
            name='lifting_capacity',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Keliamoji galia, strėlės siekis'),
        ),
        migrations.AlterField(
            model_name='document',
            name='model',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Markė/Modelis'),
        ),
        migrations.AlterField(
            model_name='document',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefonas'),
        ),
        migrations.AlterField(
            model_name='document',
            name='project_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresas'),
        ),
        migrations.AlterField(
            model_name='document',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Kiekis'),
        ),
        migrations.AlterField(
            model_name='document',
            name='received_by',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nuomininko priėmęs asmuo'),
        ),
        migrations.AlterField(
            model_name='document',
            name='receiver_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Gavėjo vardas'),
        ),
        migrations.AlterField(
            model_name='document',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Valstybinis numeris'),
        ),
        migrations.AlterField(
            model_name='document',
            name='sender_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Siuntėjo vardas'),
        ),
        migrations.AlterField(
            model_name='document',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Nuomos pradžios data'),
        ),
    ]
