# Generated by Django 5.1.3 on 2025-01-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_document_cargo_name_alter_document_client_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='delivery_info',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Pristatymas / išvežimas'),
        ),
        migrations.AddField(
            model_name='document',
            name='distance',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pravažiuota kilometrų'),
        ),
        migrations.AddField(
            model_name='document',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='El. Paštas'),
        ),
    ]
