# Generated by Django 5.1.3 on 2025-02-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_document_delivery_info_document_distance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='carrier_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Vežėjas'),
        ),
        migrations.AddField(
            model_name='document',
            name='driver_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Vairuotojo vardas'),
        ),
        migrations.AddField(
            model_name='document',
            name='loading_location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Pakrovimo vieta'),
        ),
        migrations.AddField(
            model_name='document',
            name='unloading_location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Iškrovimo vieta'),
        ),
    ]
