# Generated by Django 5.1.3 on 2025-02-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_document_carrier_name_document_driver_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='transport_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Transportavimo kaina'),
        ),
    ]
