# Generated by Django 5.1.3 on 2025-03-16 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_remove_document_transport_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=20, unique=True, verbose_name='Valstybinis numeris')),
                ('model', models.CharField(max_length=50, verbose_name='Transporto priemonės modelis')),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='carrier_name',
            field=models.CharField(default='UAB ,,KĖDAINIŲ KRANAI‘‘ Įmonės kodas 302742708 Parko g. 20, Juodkaimių k. Kėdainių r.', editable=False, max_length=255, verbose_name='Vežėjo pavadinimas ir adresas'),
        ),
        migrations.AlterField(
            model_name='document',
            name='delivered_by',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Įrangą pristatęs asmuo'),
        ),
        migrations.AlterField(
            model_name='document',
            name='received_by',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Įrangą priėmęs asmuo'),
        ),
        migrations.AlterField(
            model_name='document',
            name='registration_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.vehicle', verbose_name='Valstybinis numeris'),
        ),
    ]
