# Generated by Django 5.1.3 on 2025-03-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_vehicle_alter_document_carrier_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='registration_number',
            field=models.CharField(max_length=10, unique=True, verbose_name='Valstybinis numeris'),
        ),
    ]
